### ISSUE TITLE
es-abstract on 1.18 next is breaking app

### ISSUE THREAD

**Issue by craigmiller160** [es-shims/String.prototype.trim#10]
Cannot find module 'es-abstract/2020/RequireObjectCoercible' from '../../../string.prototype.trim/implementation.js'

Is the error message I get. es-abstract is still coming down as a 1.17 version, but this project is on 1.18-next.

This is a simple polyfill. It's a transitive dependency of another project. I'm not understanding why it needs to be on a next version of this dependency at all. Thanks.

**Comment by ljharb** [comment]
The “next” version is just a prerelease of the upcoming v1.18 minor. The issue you’re seeing is that the 2020 operations don’t exist in v1.17.

In other words, I’m not sure why this is causing a problem - string.prototype.trim should be pulling in the v1.18 prerelease, and anything that pulls in v1.17 will either dedupe and keep the 1.18, or make two copies of es-abstract, which will work fine.

Where are you getting this error? What version of which package manager are you using to install dependencies, and on what node version?

**Comment by craigmiller160** [comment]
NodeJS 14.3.0
Yarn 1.22.4

I've tried approaching this from a few different directions. No matter what, my project seems to still be pulling down a 1.17.x version.

Using the "resolutions" in package.json fixes the problem, but I'm hoping for a better solution to resolve this dependency bug. Something is causing the older version to still be pulled down.

```
"resolutions": {
    "es-abstract": "1.18.0-next.1"
  },
```

**Comment by craigmiller160** [comment]
I just upgraded yarn to the latest 1.22.10, no change in behavior.

**Comment by craigmiller160** [comment]
I get the error when running Jest tests, btw. It appears there are other polyfills in my dependency graph pulling in the older version, and it is taking precedence.

**Comment by ljharb** [comment]
This seems like a yarn 1 bug. Given that yarn 1 is unsupported, I’d suggest migrating to npm 7, which won’t have simple deduping bugs.

I’m glad the resolutions feature solves it in the interim - perhaps there’s another mitigation in the meantime. What other deps do you have that are bringing in v1.17? I could upgrade those.
